name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test_packages:
    name: Prepare dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_USER: ${{ secrets.NPM_USER }}
          NPM_PASS: ${{ secrets.NPM_PASS }}

      - name: Build api-client
        run: cd ./packages/api-client && yarn build

      - name: Test API Client (unit tests)
        run: cd ./packages/api-client && yarn test --coverage

      - name: Build SDK
        run: cd ./packages/sdk && yarn build

      - name: Test SDK (unit & integration tests)
        run: cd ./packages/sdk && yarn test --coverage
